name: deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      with:
        host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
        key: ${{secrets.SSH_KEY}} # Private or public key of the server
        username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
        script: 'cd /var/www/html && ./server_deploy.sh'
